spring:
  application:
    name: GastroRoots API
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost/GASTRO_ROOTS_DATABASE?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration