version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: GASTRO_ROOTS_DATABASE
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: GASTRO_ROOTS_DATABASE
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
