CREATE TABLE STATE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    ACRONYM VARCHAR(2) NOT NULL
);

CREATE TABLE CITY (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    STATE_ID BIGINT NOT NULL,
    FOREIGN KEY (STATE_ID) REFERENCES STATE(ID)
);

CREATE TABLE KITCHEN (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PAYMENT_FORM (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE RESTAURANT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DELIVERY_FEE DECIMAL(10, 2) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_OPEN BOOLEAN NOT NULL DEFAULT TRUE,
    REGISTRATION_DATE DATETIME NOT NULL,
    UPDATE_DATE DATETIME,
    KITCHEN_ID BIGINT NOT NULL,
    FOREIGN KEY (KITCHEN_ID) REFERENCES KITCHEN(ID)
);

CREATE TABLE ADDRESS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ZIP_CODE VARCHAR(20) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    NUMBER VARCHAR(20) NOT NULL,
    COMPLEMENT VARCHAR(255),
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY_ID BIGINT NOT NULL,
    RESTAURANT_ID BIGINT NOT NULL,
    FOREIGN KEY (CITY_ID) REFERENCES CITY(ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(ID)
);

CREATE TABLE RESTAURANT_PAYMENT_FORM (
    RESTAURANT_ID BIGINT NOT NULL,
    PAYMENT_FORM_ID BIGINT NOT NULL,
    PRIMARY KEY (RESTAURANT_ID, PAYMENT_FORM_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(ID),
    FOREIGN KEY (PAYMENT_FORM_ID) REFERENCES PAYMENT_FORM(ID)
);